import 'dart:io';

import 'package:auto_route/auto_route.dart';
import 'package:cached_network_image/cached_network_image.dart';
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:pokemon_core/pokemon_core.dart';
import 'package:pokemon_features/pokemon_features.dart' hide initMicroPackage;
import 'package:pokemon_features/src/pokemon_details/presentation/bloc/pokemon_details_bloc.dart';
import 'package:pokemon_features/src/shared/widgets/_barrel_shared_widgets.dart';
import 'package:pokemon_models/pokemon_models.dart';
import 'package:pokemon_ui_kit/pokemon_ui_kit.dart';
import 'package:skeletonizer/skeletonizer.dart';

part '../presentation/page/pokemon_details_page.dart';
part '_details_type_badges_widget.dart';
part '_dotted_divider_painter_widget.dart';
part '_header_widget.dart';
part '_pokemon_cry_widget.dart';
part '_pokemon_details_skeleton_loader.dart';
part '_pokemon_details_card_widgets/_pokemon_details_card_flavor_text_widget.dart';
part '_pokemon_details_card_widgets/_pokemon_details_card_genus_widget.dart';
part '_pokemon_details_card_widgets/_pokemon_details_card_image_widget.dart';
part '_pokemon_details_card_widgets/_pokemon_details_card_info_widget.dart';
part '_pokemon_details_card_widgets/_pokemon_details_card_widget.dart';
part '_pokemon_evolution_chain_widget.dart';
part '_pokemon_info_tile_widget.dart';
part '_pokemon_moves_widget.dart';
part '_pokemon_stats_list_widget.dart';
part '_stat_rectangle_bar_painter_widget.dart';
part '_strengths_and_weaknesses_widget.dart';
