name: pokemelos

useRootAsPackage: true

packages:
  - pokemon_base
  - pokemon_packages/**

command:
    clean:
      hooks: 
        post: melos exec --concurrency=1 -- "find . -type f \( -name '*.module.dart' -o -name '*.config.dart' -o -name '*.gm.dart' -o -name '*.freezed.dart' -o -name '*.g.dart' -o -name 'pubspec_overrides.yaml' \) -delete" 

scripts:

  analyze: melos exec -- flutter analyze

  test: melos exec -- flutter test

  build:
    steps: 
      - melos exec --concurrency=1 --ignore="pokemon_base" -- dart run build_runner build --delete-conflicting-outputs
      - melos exec --concurrency=1 --depends-on=build_runner --scope="pokemon_base" -- dart run build_runner build --delete-conflicting-outputs
    description: Run code generation in watch mode across all packages

  auto-build:
    steps: 
      - melos exec --concurrency=1 --ignore="pokemon_base" -- dart run build_runner watch --delete-conflicting-outputs
      - melos exec --concurrency=1 --depends-on=build_runner --scope="pokemon_base" -- dart run build_runner watch --delete-conflicting-outputs
    description: Run code generation in watch mode across all packages


  clean-build: melos exec --concurrency=1 --depends-on=build_runner -- melos clean && melos bootstrap && melos build

  clean-auto-build: melos exec --concurrency=1 --depends-on=build_runner -- melos clean && melos bootstrap && melos auto-build
