name: pokemelos

packages:
  - pokemon_base
  - pokemon_packages/**

scripts:
  clean: melos exec -- flutter clean
  bootstrap: melos exec -- flutter pub get
  analyze: melos exec -- flutter analyze
  test: melos exec -- flutter test
  build: flutter pub run build_runner build --delete-conflicting-outputs
  clean-build: melos exec -- melos clean && melos bootstrap && melos build
