name: pokemon_models
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.8.0
  flutter: ^3.32.0

dependencies: 
  equatable: ^2.0.8
  flutter:
    sdk: flutter
 
dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^9.0.0
